### ISSUE TITLE
Update footer on stacks.stanford.edu landing page

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/stacks#1039]
The footer on the stacks.stanford.edu landing page uses an old version of the libraries footer and has broken links. It should be replaced by the newer footer on sites like https://nta-stage.stanford.edu/

**Comment by jcoyne** [comment]
@andrewjbtw purl.stanford.edu also uses an old version of the footer, I think we want the newer design on both. I think the latest is on https://nta-stage.stanford.edu/

**Comment by andrewjbtw** [comment]
Thanks, I updated the description. I assumed purl had the right footer because the links there actually work.

**Comment by jcoyne** [comment]
@andrewjbtw can I record that you are the PO of this page?

**Comment by andrewjbtw** [comment]
Superseded by #1232
