### ISSUE TITLE
IIIF percent requests are returning 500 errors

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/stacks#1069]
Reported from purl-feedback:

>It used to be possible to request such a map sheet with IIIF margin parameters. This does not work anymore. Example:
   This works: https://stacks.stanford.edu/image/iiif/cp798vs8827/6855100/full/full/0/default.jpg
   This does not: https://stacks.stanford.edu/image/iiif/cp798vs8827/6855100/pct:3,3,77,77/full/0/default.jpg

Slack [discussion](https://stanfordlib.slack.com/archives/C05SVRXGER1/p1701901910929479) indicates this is related to #1003 

There's also an HB alert: https://app.honeybadger.io/projects/49299/faults/102165463

**Comment by hudajkhan** [comment]
For the moment, changes for #1003 had to be reverted.  https://github.com/sul-dlss/stacks/pull/1070 .  Reviewing what in the reverted approach resulted in these errors.

**Comment by jcoyne** [comment]
Fixed by #1070
