### ISSUE TITLE
Long load time for manifest -> info.json -> tiles

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/stacks#119]
I have a report from a user in UK where they are experiencing 5 second load times for some of our DRMC images. I'm trying to get the user to create a screencast so we can better understand what is going.

Is 5 sec possible?

**Comment by mejackreed** [comment]
Some example round trip times from this morning ~7:44 ET

![screen shot 2017-02-09 at 7 44 54 am](https://cloud.githubusercontent.com/assets/1656824/22783888/c1291790-ee9b-11e6-9e8a-5bdbbbda8339.png)
![screen shot 2017-02-09 at 7 44 28 am](https://cloud.githubusercontent.com/assets/1656824/22783889/c12ae552-ee9b-11e6-91bd-78e13ccc3cd1.png)

**Comment by jkeck** [comment]
@mejackreed is this coming from a js snippet you could share (or is this part of a larger codebase)?

**Comment by mejackreed** [comment]
https://github.com/mejackreed/DavidRumseyMapTab/blob/master/lib/map.js#L35-L41

From DavidRumseyMapTab. I could formalize the tests/experiment a bit more if necessary.
