### ISSUE TITLE
[production] Djatoka::Resolver#metadata is experiencing many "Connection reset by peer" errors

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/stacks#120]
The `Djatoka::Resolver` is generating many many (as in 140k occurances since 9/16) 500 server errors during the metadata resolver call (line 50 below).

```
Errno::ECONNRESET: Connection reset by peer
48     benchmark "Fetching djatoka metadata for #{@stacks_file_path}" do
49       resolver = Djatoka::Resolver.new(Settings.stacks.djatoka_url)
50       resolver.metadata(@stacks_file_path).perform
51     end
```

Here is an example URL that is failing -- but note that these are **intermittent** errors and they don't happen all the time:

  https://stacks.stanford.edu/image/iiif/kq131cs7229%252Fkq131cs7229_05_0026/4096,0,87,4096/22,/0/default.jpg

See https://app.honeybadger.io/projects/49299/faults/31212832#notice-summary

Not sure if this is helpful but on the imageserver box here's an example error message from httpd:

```
[Wed Feb 22 14:44:58 2017] [error] [client 171.67.45.21] (104)Connection reset by peer: proxy: error reading status line from remote server localhost
[Wed Feb 22 14:44:58 2017] [error] [client 171.67.45.21] proxy: Error reading from remote server returned by /adore-djatoka/resolver
```

**Comment by mejackreed** [comment]
I wonder if this could be related to the storage that is mounted.

**Comment by drh-stanford** [comment]
Yeah I dunno. The integration point is: 

`stacks ---http---> imageserver ---httpproxy---> imageserver-cache`

Where the http API call gives it a locally mounted filepath. 

It seems that the error is happening in the proxying to the imageserver-cache box and it's getting lots of error messages like this in `/var/log/messages`:

```
Feb 23 11:28:23 imageserver-cache-prod-a varnishd[18354]: Child (4387) Panic message: Assert error in http_GetHdr(), cache_http.c line 266:#012  Condition(l == strlen(hdr + 1)) not true [...]
```

But I'm not familiar with this architecture but this is what I gleemed from poking around.
