### ISSUE TITLE
Graph stacks storage growth over time

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/stacks#1211]
As part of the versioning work, we need to estimate the expected growth of stacks storage over time. This will inform decisionmaking about filesystem layout and backup strategies.

I've compiled a list of every file on /stacks with file size and modification times. This issue is to create a chart from that data to show historical trends.

The file is over 300 MB, so I've uploaded it to Google Drive ([link](https://drive.google.com/file/d/1ZGogrObwO5JwevjB62ycl0y5IHqgjN2y/view?usp=drive_link))

**Comment by cbeer** [comment]
![forecast](https://github.com/user-attachments/assets/d02201ce-bb64-471f-a648-99aad49d9879)
