### ISSUE TITLE
Confirmation of Level 0 adherence

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/stacks#128]
The profile for our image's `info.json` reports a compliance level of 0:

```json
"profile": [
  "http://iiif.io/api/image/2/level0.json"
]
```
> https://stacks.stanford.edu/image/iiif/dx799rr1936%2F0329032/info.json

 Yet in our manifests, this same image is referenced as a level 1:

```json
"resource": {
  "@id": "https://stacks.stanford.edu/image/iiif/dx799rr1936%2F0329032/full/full/0/default.jpg",
  "@type": "dctypes:Image",
  "format": "image/jpeg",
  "height": 5680,
  "width": 9368,
  "service": {
    "@context": "http://iiif.io/api/image/2/context.json",
    "@id": "https://stacks.stanford.edu/image/iiif/dx799rr1936%2F0329032",
    "profile": "http://iiif.io/api/image/2/level1.json"
  }
},
```
> https://purl.stanford.edu/dx799rr1936/iiif/manifest

Which one is the source of truth? This may be PURL issue if stacks is the source of truth.

**Comment by cbeer** [comment]
Off-hand, I'd guess stacks is the source of truth and PURL is just doing whatever the iiif-presentation gem does by default. It looks, though, that we satisfy most of the IIIF level1 compliance items, so maybe it's worth just auditing where we are and what's left to be done?

(I'm guessing we don't do base uri redirects or json-ld content negotiation, at the very least, but at the very least we should spawn some tickets for those)

**Comment by tingulfsen** [comment]
Stacks is currently inconsistently reporting compliance levels:

`curl -v https://stacks.stanford.edu/image/iiif/dx799rr1936%2F0329032/info.json
...
< X-Request-Id: c5785322-cb16-4e92-98d0-e9d35ca16d77
< Link: <http://iiif.io/api/image/2/level1.json>;rel="profile"
...
  "profile": [
    "http://iiif.io/api/image/2/level0.json"
`

**Comment by cbeer** [comment]
👍 Let's talk about adding full level 1 compliance to our current work cycle.

**Comment by mejackreed** [comment]
👏 thanks y'all
