### ISSUE TITLE
refactor access tests for easier navigation / completeness 

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/stacks#136]
e.g.:
* user logged in  / not logged in
* user at correct specific loc / at incorrect specific loc / at unknown loc
* rights at object level / file level
* world / stanford / dark
* download / no-download
* thumb / no thumb

* discover / download / view/stream / thumbs

and of course, combinations (stanford only + location based) ...

**Comment by jmartin-sul** [comment]
this was spawned by what felt like a lack of automated coverage when implementing #132
