### ISSUE TITLE
change scaleFactors to powers of 2

### ISSUE THREAD

**Issue by azaroth42** [sul-dlss/stacks#14]
In the current deployed version, the scaleFactors are, for example, `[1,2,3,4,5]` for a 17000 pixel wide image.  This means that tiles are available at 1/1, 1/2, 1/3, 1/4 and 1/5 scales.

Open Seadragon will only request factors of 2: 1/1, 1/2, 1/4, 1/8, 1/16 and so forth, and thus only 1/1, 1/2 and 1/4 are ever requested from the scaleFactors provided.

The fix (IMO) is to return scaleFactors that are powers of 2, such that the long edge of the largest scaleFactor is one step below the tilesize, thus the most zoomed out will be four tiles.

**Comment by mejackreed** [comment]
@azaroth42 when you say the following:
> such that the long edge of the largest scaleFactor is one step below the tilesize, thus the most zoomed out will be four tiles.

Is this in practice, for a given info.json response:
```json
{
... 
 "width" : 6000,
  "height" : 4000,
  "sizes" :...,
  "tiles": [
    {"width" : 512, "scaleFactors" : [1,2,4,8,16]}
  ],
 ...
}
```
So then scaleFactors can calculated by:
```ruby
long_edge = [6000, 4000].max
tile_size = 512
scale_factors = []
i = 0
while((2**i * tile_size) < long_edge) do
 scale_factors.push(2**i)
 i += 1
end
# Add one more
scale_factors.push(2**i)
```
Does this seem correct?

**Comment by azaroth42** [comment]
Yes. Though on second thoughts, I think it should be short_edge instead of long_edge.  For scrolls where there's a VERY long edge compared to the short edge, it would generate very small tiles. The other, and perhaps preferred, option would be to work off the long edge but have a lower bound of (say) 256 px for the tile size.
