### ISSUE TITLE
Stacks sometimes doesn't return images

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/stacks#144]
Instead it returned with a 500 internal server error.
https://app.honeybadger.io/projects/49299/faults/32355036#notice-summary
This was an  Errno::ECONNRESET: Connection reset by peer 
when communicating with djatoka
<img width="767" alt="screen shot 2017-07-13 at 12 57 15 pm" src="https://user-images.githubusercontent.com/92044/28180535-f7f9c3fc-67ca-11e7-91d1-b2bd4509a837.png">
That makes the embed show part of the picture.

**Comment by julianmorley** [comment]
Sounds like tomcat is running out of resources. May just be badly/not-tuned for load, or it could be being swamped by upstream requests.
