### ISSUE TITLE
Install ImageMagick 7.0.7-0 linked to OpenJPEG 2.2.0

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/stacks#156]
This version of OpenJpeg has the stanford funded speedups: https://groups.google.com/forum/#!searchin/iiif-discuss/openjpeg%7Csort:relevance/iiif-discuss/LWVEIg0-xOg/zYyxc09cAQAJ

**Comment by cbeer** [comment]
Transfered to https://github.com/sul-dlss/operations-tasks/issues/766.
