### ISSUE TITLE
[refactor] Extract DRUID id work from stacks_file

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/stacks#169]
In order to extend stacks to use a new (or more than one) adapter (i.e. riiif, cantaloupe, etc) it would be more appropriate to extract the DRUID domain specific work into it's own service object (or possibly a gem if it would be useful outside of stacks).

**Comment by aaron-collier** [comment]
Since https://github.com/sul-dlss/druid-tools exists, look at ways to include this.

**Comment by jcoyne** [comment]
@aaron-collier can this be closed?  See `StacksIdentifier`?

**Comment by aaron-collier** [comment]
Yup. closing.
