### ISSUE TITLE
"tile_width" and "tile_height" were removed in IIIF V2.

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/stacks#179]
Present here:
http://iiif.io/api/image/1.1/#5-image-information-request

Not here:
http://iiif.io/api/image/2.0/#image-information

**Comment by cbeer** [comment]
👌 if we can verify that openseadragon doesn't use the information, let's dump it. `tiles` is the replacement, yeah?

**Comment by cbeer** [comment]
Verified. Remove away.

**Comment by aaron-collier** [comment]
Do we just want to remove `tile_width` and `tile_height` or do we want to add the `tiles` section? There is a `scaleFactors` that is expected in the `tiles` section.

**Comment by cbeer** [comment]
I think we already have `tiles`, see https://stacks.stanford.edu/image/iiif/degraded_mt702pj0399%252F2011-023NIEL-1978-b11_1.2_0012/info.json + https://stacks.stanford.edu/image/iiif/ms429pw9037%252Fms429pw9037_00_0001/info.json.

**Comment by jcoyne** [comment]
See #198
