### ISSUE TITLE
pct:50 pct:200 are not valid region values

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/stacks#186]
What is going on here: 
https://github.com/sul-dlss/stacks/blob/88a422bb6ceccc493031ccf68cf29c40ed77a3fe/spec/models/stacks_image_spec.rb#L122-L123

**Comment by cbeer** [comment]
No idea; it traces back to the original digital stacks sinatra codebase. Maybe it was part of a very early IIIF spec? I can dig further, or I can check logs and see if it gets used.

**Comment by jcoyne** [comment]
Yeah, I'm seeing this as potentially problematic: https://github.com/sul-dlss/stacks/commit/5c2a25a950792a72831e742d9e83a0f85a1041ca#diff-e2d76dc51f57f2472765a1f10341609aR49

**Comment by cbeer** [comment]
We're 👌 to drop support for these invalid region values without notice or replacement. They weren't use in the last calendar year, at least.
