### ISSUE TITLE
Should we be using tiles in the jp2 rather than specifying our own tile sizes?

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/stacks#201]
This would be a more efficient way to extract images if the jp2 has tiles.

**Comment by cbeer** [comment]
We need to deliver "small" tiles for no-download content. I think we picked `1024x1024` as a reasonable size for delivering to users based on some analysis someone did sometime ago; perhaps the ideal size has since changed?

**Comment by jcoyne** [comment]
I think this is a blocker because the IiifMetadataService does not force the tiles to 256 as the DjatokaMetadataService (for restricted images).  Do we know if this is important to copy over?  I'm not sure why it's important to have a small tile size, nor do I understand why 256 was picked.

**Comment by cbeer** [comment]
Yes, it's essential for no-download content. We can happily revisit non-restricted tile sizes, but for no-download content, we need to advertise tiles smaller than 400px long edge (and 256 was a convenient power-of-2).
