### ISSUE TITLE
Problems with delivery of large JP2s (or JPEGs generated from them)

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/stacks#23]
Summary:
- it is expensive to generate downloadable jpgs from jp2s when the jpg exceeds a certain size (in the neighborhood of 10K px on the long edge)

E-mail thread for analysis:

Ben-

Thanks for initiating this investigation and moving the ball forward.  Indeed this is a bad user experience, first and foremost, that we should correct. 

I know the the web team has ideas, which include excluding the largest sizes in the declaration of sizes in the info.json so that our IIIF-compatible clients, AND OTHERS, will not be able to request sizes we cannot deliver. I think the highest priority is to address the user experience issue given our current environment, and not offer downloads on image sizes we cannot deliver.  

This may disappoint some who want download of the full image, but these things are big and in many cases 75% or 50% of full will still be a huge and suitable image.

This doesn’t eliminate the need to address the performance issue, but I think reduces its urgency.  We should consider if this is worth putting in the backlog of the soon to be formed sprint team that will be working on the Stacks.  That team will need to focus on and prioritize media, of course, but this at least should be ticketed and queued.  Would you be so kind as to create a ticket in the Stacks github project, or add this thread to the existing ticket if it already exists?

Cheers,

Stu

On Jan 26, 2016, at 9:05 PM, Benjamin L Albritton blalbrit@stanford.edu wrote:

Dear all,

Given the ongoing nature of problems we have had with delivery of large JP2s (specifically, generation of JPEGs at size levels above 10K pixels on the long edge - most recently raised by David Rumsey in relation to download of some of his large maps), I asked Sean Martin to investigate whether it was a JP2-recipe-related, image-server-related, or "other" issue. Sean's fantastic detailed analysis is below, along with the attached raw data from his analysis. My take-away from this is as follows:
​the method by which we encode our JP2s is not a problem
the tiled delivery of very large JP2s is not a problem
the main issue seems to be the cost of generating very large jpegs on-the-fly - and I think Chris and Erin could provide some useful feedback on options for how to handle this issue. Sean's concluding paragraphs point toward the following: 
​making the generation/download of the jpegs (or just v. large jpegs) an asynchronous process
assess the impact of the current practice on server load (what happens to performance when someone is trying to generate a large jpeg?)
is Djatoka using the cjpeg library? are there other ways to tune what we already have in place?
Many thanks to Sean for the analysis - Stu, Lynn, Tom - how shall we move this forward?

Best,

Ben

From: Sean Martin seanmartin@fastmail.co.uk
Sent: Sunday, January 24, 2016 10:51 AM
To: Benjamin L Albritton
Subject: Image delivery investigation

Hi Ben

As promised, I've taken a look at the situation you described.

The problem

You directed me to this image: https://purl.stanford.edu/wv304jy9677 and you had three queries:
If you try to download either of the two largest sizes, failure happens 
the actual zooming in the tiled object in the embedded viewer doesn't seem to be going to full size (when compared with the jp2 viewed in another viewer)
 https://stacks.stanford.edu/image/iiif/wv304jy9677%252Fwv304jy9677_05_0001/full/full/0/default.jpg fails, though lower pct parameters succeed, reinforcing 2) above. 
Nature of what's happening

The web page shows a list of download options which progressively double in size up to the full resolution of the image. Its worth considering the corresponding activity on the server which involves a two step process:
decode the jpeg 2000 image and produce an intermediate bit mapped image, which is written out as a intermediate file, or it might be held in memory,
encode the intermediate file into a jpeg, which is then delivered. 
As one steps down the list, both the width and the height double, and the number of pixels increases by a factor of 4. With small images overheads dominate, but with larger images the decode and encode operations dominate. The work that the server needs to do increases by a factor of 4 for each step down the list.

For example, for the full size image, a 77Mb JP2 is decoded and a 400 Mega pixel image is created which is held in a 1.227 Gb intermediate file. This is then encoded to produce a 65 Mb jpeg file. The delivery cannot start until the encoding has been completed. That's a lot of work!

Modelling on a PC

I have rerun the decode/encode pair of operations on a medium speed desktop PC. The decode is with kakadu (kdu) and the encode is with cjeg, a widely used jpeg library. There is a faster library available, but cjpeg is considered for many production applications. I used a degree of quality/compression to roughly match that delivered from the Stanford server. The overall timings for decode followed by decode for the full size, half size and quarter size images were around 21, 7 and 2.5 seconds respectively. These are indicative figures as they vary each time they are run. These figures shows roughly a factor of three increase with each step toward greater resolution. Hence this is slightly better than than the factor of 4 increase in workload.

Timings from the Stanford server

I conducted a similar exercise with downloads from the Stanford server noting the delay before the download starts and also the duration of the download. The data was captured using a proxy server. For the larger downloads the delay before the download starts show a similar increase by a factor of three increase with each step, though there was one anomaly. I tried to rerun this test, but I think the image was cached somewhere, so it appeared very quickly, and the rerun was thwarted. However, the pattern of one set of data roughly matches the pattern of the set of data from my PC. The download of the half size image from Stanford started 37 seconds after the request was made, and the download completed OK after a further 65 seconds. The request for the full size image timed out at almost exactly 60 seconds with an error message that the image cannot be displayed, because it contains errors. However, its fairly clear that it is a time-out and not a problem with the image, hence the error message is misleading. (If one takes the previous figure of 37 seconds, and multiplies by three then its well over 60 seconds before the image would be ready ..)

Full data - this is available in the attached spreadsheet, which should be reasonably self explanatory, given this summary, but please let me know if you have any queries/comments on it.

Zooming and "full/full" request

Regarding your points 2 and 3: with the proxy server I was able to see the request and response traffic as I zoomed into the image. I did not see any failed requests, and at least one of the requests was for a tile portion at full resolution, so I would expect that it was displayed at full resolution. I would be happy to retest this if you would like.

You quoted in 3 above a URL which has a "full/full" request. It is a request for the full image at full resolution, and an error message was displayed almost immediately. Interestingly the logic of the request is similar to the full download, but a different syntax is used. The download uses "full/25452,16460" instead of "full/full" and it takes 60 seconds to time out. Clearly the server behaviour is different, but I do not know why. Again, the error message, is, I believe, misleading. The server did not want to do the task, and there was nothing wrong with the image.

Conclusions/comments

The larger downloads, and especially the full download, induce a huge amount of work on the server. The performance of the Stanford server is broadly in line with that of my desktop PC. Hence, I conclude that I doubt there is anything particularly wrong with the server, it's configuration, or the JPEG 2000 image. However, the way in which the download is managed does not work well with downloads of extra large images. Currently, the web page makes a synchronous request to the server (e.g. a request is made, and it expects a response within a short period, say 30-60 seconds). However the decode/encode operation takes a similar period of time. We considered something quite similar at the BL for downloads, about making a download process asynchronous, whereby a request is made and acknowledged immediately, the server would queue the request, and process it when it can, and the web page would poll the server until it indicates that it has the required file available. One could smarten this up to include how many images are being processed before you, etc.

There is a second and possibly more important point, but where I am making several assumptions. Such a download request completely swamps the image server while the image is being created - this is perhaps a "user induced denial of service attack", as the image server is likely to be quite unresponsive to other users during this period - it will be go slow for a minute or so. Hence it may be best to move this out to a separate download server, which is a standard image server. Clearly a knowledgeable user could construct requests which constitute a denial of service attack, but this puts it "on a plate" making it easy to happen. (Obviously IIIF was designed to deliver tiles for display, and so such tiles are small, whereas the downloads are huge. If one was concerned about denial of service, one could block requests for large images, and allow them only on a queue based download image server, where the queue gives a lot of protection.)

Finally, a supplementary comment, you mentioned you are using djatoka. The Norwegians noticed that it had a bottleneck with the java library for jpeg encoding, and they modified it to use cjpeg. I would guess that you are using djatoka modified to use cjpeg, as the responses are fairly fast, but this is worth checking. I have noticed with my own web server an issue with time-outs - it invokes kakadu and if it is unresponsive then the web server can deem that the launched process has timed out, and so produce an error. Time outs can occur in several places ....

I hope this quick investigation and notes are helpful. However, I'm sorry I don't think there are any quick fixes for this!

All best

Sean

**Comment by azaroth42** [comment]
We should update pre-emptively to Image API 2.1 with the maximum size features, otherwise we'll end up doing the same work twice.

See: http://iiif.io/api/image/2.1/#profile-description

**Comment by cbeer** [comment]
:+1:. We should also determine what our maximum size actually is.

**Comment by mejackreed** [comment]
Does OSD adhere to 2.1? Maybe that should be on the OSD backlog too? https://github.com/openseadragon/openseadragon/search?utf8=%E2%9C%93&q=maxHeight+OR+maxWidth&type=Code
