### ISSUE TITLE
[Stacks/prod] JSON::ParserError: 765: unexpected token at ''

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/stacks#241]
## Backtrace

    line 52 of [PROJECT_ROOT]/app/services/iiif_metadata_service.rb: json
    line 33 of [PROJECT_ROOT]/app/services/iiif_metadata_service.rb: image_width
    line 50 of [PROJECT_ROOT]/app/models/stacks_image.rb: image_width

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49299/faults/34745233)

**Comment by aaron-collier** [comment]
#246 - in progress
