### ISSUE TITLE
[Stacks/prod] NoMethodError: undefined method `/' for nil:NilClass

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/stacks#242]
## Backtrace

    line 63 of [PROJECT_ROOT]/app/models/projection.rb: width_for_aspect_ratio
    line 47 of [PROJECT_ROOT]/app/models/projection.rb: explicit_tile_dimensions
    line 33 of [PROJECT_ROOT]/app/models/projection.rb: tile_dimensions

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49299/faults/34708899)

**Comment by jcoyne** [comment]
This has been replaced by #254
