### ISSUE TITLE
[Stacks/prod] ArgumentError: wrong number of arguments (given 0, expected 1..2)

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/stacks#252]
## Backtrace

    line 63 of [PROJECT_ROOT]/app/controllers/application_controller.rb: token_user
    line 45 of [PROJECT_ROOT]/app/controllers/application_controller.rb: bearer_auth_user
    line 19 of [PROJECT_ROOT]/app/controllers/application_controller.rb: current_user

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49299/faults/34617984)

URI: https://stacks.stanford.edu/file/druid:xy547ss8747/Panasonic_Winter_Report2014.pdf

This only appears to happen when the user agent is Microsoft Word

**Comment by jcoyne** [comment]
Closed by #221
