### ISSUE TITLE
[Stacks/prod] RuntimeError: There was a problem fetching http://imageserver-prod.stanford.edu/iiif/2/st%2F427%2Fhj%2F4545%2FT0000001.jp2/info.json. Server returned 500

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/stacks#280]
## Backtrace

    line 46 of [PROJECT_ROOT]/app/services/iiif_metadata_service.rb: block in retrieve
    line 44 of [PROJECT_ROOT]/app/services/iiif_metadata_service.rb: retrieve
    line 53 of [PROJECT_ROOT]/app/services/iiif_metadata_service.rb: json

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49299/faults/34803655)

**Comment by jcoyne** [comment]
Replaced by #293
