### ISSUE TITLE
large images disappearing on deep zoom

### ISSUE THREAD

**Issue by snydman** [sul-dlss/stacks#349]
Zoom as far in as possible with this object:  https://purl.stanford.edu/nf274ng7905/iiif/manifest

In both Universal Viewer (in SUL-Embed) the object disappears on deepest zoom. It also occurs in Mirador.  Is this a Stacks issue, or a problem with both viewers?

**Comment by mejackreed** [comment]
I'm thinking this might be an issue with OpenSeadragon on first glance. Stacks seems to be handling the images that are being requested.

**Comment by mejackreed** [comment]
It works ok in Leaflet-IIIF: http://mejackreed.github.io/Leaflet-IIIF/examples/index.html?url=https://stacks.stanford.edu/image/iiif/nf274ng7905%2Fnf274ng7905_0001/info.json
