### ISSUE TITLE
Can we provide a special fail message for location auth that fails?

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/stacks#353]
Related to a comment from @hannahfrost :

> Hannah: went to this page logged in and not in authorized location. Thumbnail visible. Clicked multi-page view and all the other images just sit-and-spin as loading. It's acceptable that the content is appropriately restricted, but a message in the viewer about why content is not loading is recommended. Better yet - would be great if it never looked like content is trying to load when we do not expect it to.

This is for content that is location restricted.

## br711ss4585

**Comment by cbeer** [comment]
Fixed with M3?
