### ISSUE TITLE
Implement Auth for non-image content rendered in UV in Stacks/PURL/Embed

### ISSUE THREAD

**Issue by snydman** [sul-dlss/stacks#444]
There is high demand to support auth for non-image content, and in particular PDF's.  @hannahfrost has received multiple requests for this. We had been waiting for support in UV, and a pattern/approach from Digirati.  

This requires IIIF v3 support, which we only make available for SDR objects tagged as documents or 3d objects.

---
 
Update from Digirati: 

UV now supports auth on a wide range of external resources, for example:

https://universalviewer.io/examples/#?c=&m=&s=&cv=&manifest=https%3A%2F%2Fiiifauth.digtest.co.uk%2Fmanifest%2F21_av_lego

This follows the candidate next gen auth spec I developed in this issue - https://github.com/IIIF/api/issues/1290#issuecomment-414707643 – I went through the approach on a couple of AV calls (Tommy has seen it). Obviously there’s a big warning around this in that it’s an extension of the current auth spec. But I hope that IIIF Auth 2.0 will look substantially like this, and the UV understands this pattern.

Tests and examples: https://iiifauth.digtest.co.uk/

There is even an approach for adaptive bit rate media. This is where the auth spec stops and community patterns take over, as discussed in that issue.

Apart from the diagram, none of this is written in prototype spec form. That is something we will probably need to decide priorities about in Edinburgh (both Auth and Search need to be aligned with Presentation 3). But there should be enough in my test site to guide a server-side implementation, and I’m obviously happy to provide help on that.

**Comment by hannahfrost** [comment]
Here is a doc with some use cases listed: https://docs.google.com/document/d/1VzWMKPguoS1Za7baJro4WU8Nfy0XU8ttenGB9ZCU5yo/edit#

One question about scope: should I include cases for objects of "file" type with single non-PDF file or multiple files of any format?

Bring on your questions! Thanks for looking into this.

**Comment by cbeer** [comment]
I spent some time trying to digest the diagrams of the new auth stuff; I think there's several hours of work involved (plus whatever time is necessary to deal with updating UV), but it may be worth holding off until there's at least a draft spec for this. Hopefully something useful comes out of Edinburgh.

**Comment by hannahfrost** [comment]
I think this issue can be closed, because we no longer use the UV viewer. Any open needs related to auth, non-image content and IIIF v3 can be ticketed separately as needed.
