### ISSUE TITLE
stacks can't recognize the same IP address in more than one user location

### ISSUE THREAD

**Issue by tallenaz** [sul-dlss/stacks#473]
When a user's static IP addresses is specified in more than one location, as seen in [shared_configs](https://github.com/sul-dlss/shared_configs/blob/sul-stacks-prod/config/settings/production.yml#L47-L65), the application is unaware of more than one of the locations. 

Looking at [code from the `ApprovedLocation` class](https://github.com/sul-dlss/stacks/blob/216ccde5b655c88f663e1913061e648c15d04be8/app/models/approved_location.rb#L25-L27) we see something like:
```ruby
Settings.user.locations.find { |_,ip_addresses| ip_addresses.include?(ip_address1) }
 => [:location1, [ip_address1, ip_address2]] 
```
even if `:location2` also includes `ip_address1`

We need the ability for stacks to recognize multiple approved locations for the same ip address.

**Comment by hannahfrost** [comment]
@anarchivist Not sure of the process for nominating bugs for an Access Team maintenance work cycle. Is there one? If so, I will happily follow it and propose this one.

**Comment by anarchivist** [comment]
thanks @hannahfrost - I don't think we have an official process (something to fix!) but we do have a board for nomination. I'll add it for our next maintenance run which will come in October.
