### ISSUE TITLE
Evaluate stream from HTTP body

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/stacks#565]
Potentially a performance boost.

See https://github.com/emory-libraries/dlp-curate/pull/1080

**Comment by cbeer** [comment]
I think we are? https://github.com/sul-dlss/stacks/blob/master/app/controllers/iiif_controller.rb#L31

**Comment by mejackreed** [comment]
Gotcha, I wasn't sure if that was the case by just setting the `response_body` or if we needed to do something else like this: https://github.com/httprb/http/wiki/Response-Handling#body

**Comment by mejackreed** [comment]
Looks like we already do this as the response is enumerable
