### ISSUE TITLE
Numerous images not displaying on Fitch exhibit

### ISSUE THREAD

**Issue by caaster** [sul-dlss/stacks#579]
Reported by a user. Numerous images are not displaying on the Fitch exhibit. Please check out this browse category to see ~30+ images that don't display: https://exhibits.stanford.edu/fitch/browse/martin-luther-king-jr-funeral-1968. I checked rights and content metadata in Argo for a couple of these images that don't display, and I am not seeing any reason why they shouldn't display. What am I missing?

- 

E.g.:
https://stacks.stanford.edu/image/iiif/hx827np4755%2F78_0035_CSK_Nixon4352_6A/full/!400,400/0/default.jpg
https://stacks.stanford.edu/image/iiif/zp592fh4558%252F2597036/0,0,8192,7029/1024,/0/default.jpg
https://stacks.stanford.edu/image/iiif/zp592fh4558%252F2597036/0,0,8192,7029/1024,/0/default.jpg
https://stacks.stanford.edu/image/iiif/zp592fh4558%252F2597036/0,0,8192,7029/1024,/0/default.jpg

**Comment by cbeer** [comment]
Transferred to sul-dlss/stacks for the lack of a better place. 

It's hard to say for sure, but this seems like fall-out from the operating system migration. On our old imageservers, we were running cantaloupe and (presumably) kakadu 7.1 (from 2013, perhaps  older), but as part of the  migration we  updated to kakadu 7.10.2 (from 2019). With 7.10.x, there's apparently a known bug similar to what we're seeing  (referenced by https://github.com/bodleian/image-processing/issues/29, but yahoo groups has gone away so who knows...) that affects some fraction of a percent of our images (Fitch seemingly the hardest hit, but SHPC and some scanned books popped up in our analysis.. presumably they shared a common production workflow?).

Kakadu 8 fixes this particular issue, at least, but is incompatible with our Centos 7 servers (despite  their claims to the contrary).

While evaluating other options, but to mitigate this issue, we've temporarily downgraded to kakadu 7.9, which doesn't have the same issue at least, but is measurably slower and misses out on some security hardening.

I'm leaving this ticket open while we determine our permanent strategy.

**Comment by anarchivist** [comment]
I'm going to close this issue and spin up a new one about permanent strategy.
