### ISSUE TITLE
[Stacks/stage] NoMethodError: undefined method `include?' for nil:NilClass

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/stacks#678]
## Backtrace

    line 59 of [PROJECT_ROOT]/app/models/user.rb: decode_token
    line 44 of [PROJECT_ROOT]/app/models/user.rb: append_jwt_token
    line 86 of [PROJECT_ROOT]/app/controllers/cdl_controller.rb: renew

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49299/faults/67353093)

**Comment by jkeck** [comment]
I believe we addressed this at the time this error cropped up
