### ISSUE TITLE
Use CORS headers that will enable web archive replay of web archive files served from Stacks

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/stacks#782]
**Use case**

This comes from Stanford University Press, which is using web archiving as a way of preserving and providing access to certain publications. They would like to be able to use [replayweb.page](https://replayweb.page/) to serve files deposited in SDR, such as 

https://stacks.stanford.edu/file/druid:yg504wh6319/yg504wh6319_wmg.wacz

which has this Purl: https://purl.stanford.edu/yg504wh6319 

Currently, sourcing that file for use with replayweb.page is returning a 404 error.
 
**Possible solution**

Ilya Kremer, developer of replayweb.page, took a look at how Stacks serves files and thinks there’s an issue related to CORS headers. He suggests the following change may resolve the issue:
 
>“The main issue seems to be lack of support for the OPTIONS preflight request needed for CORS.
>
>The SDR endpoint should respond to an OPTIONS request with:
>Access-Control-Allow-Origin: *
>Access-Control-Allow-Headers: Range
>
>Currently, it responds with a 404.”

**Comment by peterchanws** [comment]
Use case 2

Archive.Web.Page can crawl Instagram sites which Archive-It, our web archiving service provider, cannot. For Instagram sites, we can crawl the sites using Archive.Web.Page and store the warc files in SDR.

**Comment by ikreymer** [comment]
Thanks for fixing! I assume it may be a bit before the fix is deployed to production on stacks, right? (Just wondering so can test!)

**Comment by anarchivist** [comment]
@ikreymer Most of our production deploys happen on Monday, so I'd check around mid-day Pacific Time then?
