### ISSUE TITLE
Users not logged in getting dumped to stacks homepage

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/stacks#839]
We've gotten reports recently from users who, after being prompted to login, are getting dumped to the Digital Stacks homepage.  Both Mark and I could recreate it using this record: https://searchworks.stanford.edu/view/xh917cq6431

Steps taken:
1. Opened an incognito window and navigated to https://searchworks.stanford.edu/view/xh917cq6431
2. Clicked on .docx link in the viewer (which is going to https://stacks.stanford.edu/file/druid:xh917cq6431/M.A.%20Capstone-%20Indigenous%20design%20process.docx)
2. New tab opened and went through authentication. After auth was complete, saw the [Digital stacks homepage](https://stacks.stanford.edu/).
3. Closed the tab and re-clicked on the .docx link. New tab briefly went through authentication, but I still got dumped onto the Digital Stacks homepage.
4. After clicking the link several times (and this is inconsistent - sometimes it was the third try, sometimes the fifth), I finally saw the download prompt.

Really should work the first time after log in.

**Comment by cbeer** [comment]
Is this chrome-only?

![Screen Shot 2021-11-15 at 09 18 28](https://user-images.githubusercontent.com/111218/141825531-5673d570-0ea5-4e5d-9bc6-07e1de6e96ca.png)

**Comment by saseestone** [comment]
Yes, I was in Chrome (Version 95.0.4638.69)

**Comment by cbeer** [comment]
Seems like a Shibboleth/Chrome compatibility issue that we'll need ops to resolve. There's some information at:
 
https://shibboleth.atlassian.net/wiki/spaces/IDP4/pages/1284276231/SameSite
https://shibboleth.atlassian.net/wiki/spaces/DEV/pages/1181253974

and some indication Shibboleth 4.x may be fine 🤷‍♂️

**Comment by anarchivist** [comment]
related tickets: [VUF-8540](https://jirasul.stanford.edu/jira/browse/VUF-8540), [VUF-8538](https://jirasul.stanford.edu/jira/browse/VUF-8538),

**Comment by cbeer** [comment]
fixed  by https://github.com/sul-dlss/puppet/pull/7244
