### ISSUE TITLE
iiif info.json responses don't url-encode identifiers

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/stacks#864]
this issue is via @mapninja and related to supporting manifest import in the new [allmaps viewer](https://viewer.allmaps.org/).

our presentation v2 manifests currently url-encodes a slash (`%2F`) in between the DRUID and filename of stacks URLs:
https://github.com/sul-dlss/purl/blob/835363d0dfc3cf05ba5ec26560ec4eb3903b72c4/app/models/iiif_presentation_manifest.rb#L360

...resulting in URLs like: `https://stacks.stanford.edu/image/iiif/wy534zh7137%2FSULAIR_rosette`. this URL resolves to the path `https://stacks.stanford.edu/image/iiif/wy534zh7137/SULAIR_rosette`, but the info.json response at that URL does _not_ encode the slash, resulting in `https://stacks.stanford.edu/image/iiif/wy534zh7137/SULAIR_rosette`. (see for example https://purl.stanford.edu/tc010rc2373/iiif/manifest).

the [prezi v2 spec](https://iiif.io/api/presentation/2.1/#requests) on the "prefix" part of the URL scheme says:
> The prefix may contain multiple path segments, delimited by slashes, but all other special characters must be encoded.

~not positive this is the right part of the spec, but it seems like encoding the `/` specifically is discouraged. this makes sense, since opening URLs like this in a browser causes the `%2F` to become double-url-encoded as `%252F`...and you can keep doing this forever to make longer and longer URLs!~

the [image v2 spec](https://iiif.io/api/image/2.1/#identifier) says that:
> The API places no restrictions on the form of the identifiers that a server may use or support. All special characters (e.g. ? or #) must be URI encoded to avoid unpredictable client behaviors. The URI syntax relies upon slash (/) separators so any slashes in the identifier must be URI encoded (also called “percent encoded”). 

and our identifiers are often a PURL joined to a filename with a slash, which should be encoded.

the allmaps viewer currently interprets this mismatch as an error and does not parse Stanford manifests where the @id values differ.

**Comment by mapninja** [comment]
Auth API depends on mismatched @ids, but given the encoding requirements of the @ids, NOT encoding one of them, is not a valid way to meet this need.

**Comment by mapninja** [comment]
So, this resource is behind Auth, but it does appear that the @id mismatch for Auth workflows is being accomplished by using a non-encoded @id in the info.json. So, a feature, not a bug. 

`
Manifest: | https://stacks.stanford.edu/image/iiif/bd117rc5047%2Fbd117rc5047_00_0001

info.json: | https://stacks.stanford.edu/image/iiif/bd117rc5047/bd117rc5047_00_0001
`

**Comment by thatbudakguy** [comment]
Copying @blalbrit's analysis here:
> So - it seems like there might be two issues at play here:
>
> -    a discrepancy between our presentation API (which correctly codes the internal slash in the identifier section) and our image API - if we follow the service @id from the manifest, the %2F gets rewritten to %252F (there was an old Apache rewrite module bug that did this - could this be a similar issue?)
> -    an issue in our image API implementation that is not correctly replacing the internal slash within the identifier with a %2F in the @id for the info.json document

For the former issue, although our current behavior is certainly not what one might expect, I don't think it's in violation of the spec, since as @mapninja mentioned these values need to be allowed to differ as part of the IIIF auth workflow. Also, all versions of the @id still resolve to the correct document, so the links aren't really "broken".

For the latter issue, it seems like non-encoded @id values _do_ violate the spec. However, remediating this seems like it won't be trivial. I took a pass at forcing the @ids to be encoded with this commit: https://github.com/sul-dlss/stacks/commit/00977f7269aded8941e6dea95247119444701e64, which seemed to have the desired effect. But, when @cbeer and I viewed some permission-restricted items in stacks using this change, a bug was introduced that prevented the full-resolution version of the image from being shown. We confirmed that the bug would be introduced with this change. Probably this is related to IIIF auth, but the implications could be quite broad, and investigating it will take time. The access team has an upcoming maintenance workcycle beginning the week of June 6, which might be a good time to start this investigation.

**Comment by thatbudakguy** [comment]
copying here @cbeer's note on the original proposal to change the manifest instead of the info.json response:

> I'm reopening this for our further consideration. If we stop encoding slashes, we can stop fighting against Rails, browsers, etc. We're ok spec-wise if we just imagine this as shuffling the initial druid into to the IIIF service prefix, e.g.:
> 
> IIIF Image URL: {scheme}://{server}{/prefix}/{identifier}
> 
> https://stacks.stanford.edu/image/iiif/vg994wz9415%252Fvg994wz9415_0001/info.json server: stacks.stanford.edu prefix: /image/iiif/ identifier: vg994wz9415%252Fvg994wz9415_0001
> 
> [https://stacks.stanford.edu/image/iiif/vg994wz9415/vg994wz9415_0001/info.json](https://stacks.stanford.edu/image/iiif/vg994wz9415%252Fvg994wz9415_0001/info.json) server: stacks.stanford.edu prefix: /image/iiif/vg994wz9415 identifier: vg994wz9415_0001
> 
> This is probably preferable than trying to change things on stacks to avoid anything breaking (e.g. clients relying on particular encodings or pre-existing annotations). That said, we make no claims about the persistence or durability of stacks links, and our self-generated annotations all seem to be (appropriately) canvas-level... so maybe rejecting the encoded format is something to consider for the future.

that change (https://github.com/sul-dlss/purl/pull/560) is now deployed to `sul-purl-uat`, so manifests there should have an `@id` value for image resources that does not encode the final slash. as chris mentions, this effectively means that the final portion of the URL (which often indicates the particular page or canvas) is the identifier, and each resource or item is its own "service".

**Comment by thatbudakguy** [comment]
checklist for me:

- [ ] redeploy change to UAT
- [ ] check PURL fixtures in spreadsheet to make sure nothing broke
